"""Skewed-popularity multi-anchor stress workload to expose LPB win on sglang.

Hypothesis: GSP and dev/intralayer Path A came up tied because either (a)
no eviction pressure (huge mamba pool) or (b) uniform hit distribution
across snapshots (LPB tie-breaks to recency = LRU). This driver creates
the textbook LPB-favorable case:

  * K=12 distinct system prompts (~12K tokens each), each generated by
    a fixed-seed PRNG to be deterministic across modes and trials.
  * Server launched with --max-mamba-cache-size=4 → can't fit all 12
    snapshots → eviction is forced on every new-group request.
  * Traffic is Zipf-biased: group i is chosen with weight ~1/i^alpha
    (alpha=1.5). Groups 1-3 are very hot; groups 9-12 are rare.

Under LRU eviction, snapshots rotate by recency. If traffic burstily
hits a cold group (say group 11), it'll evict whichever snapshot was
least-recently used — possibly a hot group's. The next hot-group
query then has to rebuild the snapshot, paying the full 12K-token
prefill cost.

Under LPB eviction, the cold group has hit_count ≈ 1, denominator
≈ 32 MB → priority ≈ 3e-8. Hot groups have hit_count ≈ 50,
denominator ≈ 32 MB → priority ≈ 1.5e-6. So cold groups have ~50x
lower priority → they get evicted FIRST. Hot snapshots stay
resident; hot-group queries hit the cache.

Outputs land in vllm-songyang/dev/intralayer/runs/sglang_skewed/.
"""

import argparse
import asyncio
import json
import os
import random
import time
from pathlib import Path
from typing import Optional

import aiohttp


def gen_synthetic_prompt(seed: int, target_tokens: int, tokenizer) -> str:
    """Generate a deterministic ~12K-token prompt from a seed.
    Uses tokenizer's vocab to construct token IDs, then decode.
    """
    rng = random.Random(seed)
    vocab_size = tokenizer.vocab_size
    # Avoid special tokens (typically <100)
    ids = [rng.randint(200, vocab_size - 200) for _ in range(target_tokens)]
    text = tokenizer.decode(ids, skip_special_tokens=False)
    return text


def zipf_weights(n: int, alpha: float) -> list[float]:
    raw = [1.0 / ((i + 1) ** alpha) for i in range(n)]
    s = sum(raw)
    return [r / s for r in raw]


async def issue_one(session, port, prompt, max_new_tokens=16):
    payload = {
        "text": prompt,
        "sampling_params": {"max_new_tokens": max_new_tokens, "temperature": 0.0},
    }
    t0 = time.monotonic()
    async with session.post(f"http://127.0.0.1:{port}/generate",
                            json=payload, timeout=120) as resp:
        data = await resp.json()
    wall = time.monotonic() - t0
    cached = 0
    if "meta_info" in data:
        cached = int(data["meta_info"].get("cached_tokens", 0))
    return {"wall": wall, "cached": cached}


async def run_load(prompts, group_ids, port, rps, max_new_tokens):
    """Send all prompts at a Poisson-style steady rate RPS. Return per-req records."""
    records = []
    async with aiohttp.ClientSession() as session:
        tasks = []

        async def schedule_one(i, prompt, gid, delay):
            await asyncio.sleep(delay)
            r = await issue_one(session, port, prompt, max_new_tokens)
            r["group"] = gid
            r["seq"] = i
            return r

        t = 0.0
        for i, (p, g) in enumerate(zip(prompts, group_ids)):
            tasks.append(asyncio.create_task(schedule_one(i, p, g, t)))
            t += 1.0 / rps
        for fut in asyncio.as_completed(tasks):
            records.append(await fut)
    records.sort(key=lambda r: r["seq"])
    return records


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", required=True,
                    help="Label only — controls output filename and "
                         "log prefix, not behavior. Common values: "
                         "recency, lpb, off, intra, inter, both.")
    ap.add_argument("--trial", type=int, default=1)
    ap.add_argument("--port", type=int, default=30099)
    ap.add_argument("--model", default="Qwen/Qwen3.5-35B-A3B")
    ap.add_argument("--num-groups", type=int, default=12)
    ap.add_argument("--num-prompts", type=int, default=300)
    ap.add_argument("--sys-prompt-tokens", type=int, default=12000)
    ap.add_argument("--question-tokens", type=int, default=64)
    ap.add_argument("--rps", type=float, default=2.0)
    ap.add_argument("--alpha", type=float, default=1.5,
                    help="Zipf exponent; higher = more skewed")
    ap.add_argument("--out-base", default="/scratch/yuzhou/projects/vllm-songyang/dev/intralayer/runs/sglang_skewed")
    ap.add_argument("--max-new-tokens", type=int, default=16)
    args = ap.parse_args()

    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)

    out = Path(args.out_base); out.mkdir(parents=True, exist_ok=True)
    fname = out / f"{args.arm}_t{args.trial}.json"

    # Generate K system prompts deterministically
    print(f"[{args.arm} t{args.trial}] Generating {args.num_groups} system prompts "
          f"({args.sys_prompt_tokens} tokens each)...")
    sys_prompts = [
        gen_synthetic_prompt(seed=12345 + g,
                             target_tokens=args.sys_prompt_tokens,
                             tokenizer=tokenizer)
        for g in range(args.num_groups)
    ]
    # Verify token counts
    sys_lens = [len(tokenizer.encode(p)) for p in sys_prompts]
    print(f"[{args.arm} t{args.trial}] sys lens: min={min(sys_lens)} max={max(sys_lens)} mean={sum(sys_lens)/len(sys_lens):.0f}")

    # Build prompt sequence with Zipf-biased group selection
    rng = random.Random(2000 + args.trial)
    weights = zipf_weights(args.num_groups, args.alpha)
    print(f"[{args.arm} t{args.trial}] Zipf weights (alpha={args.alpha}): {[f'{w:.3f}' for w in weights]}")
    group_seq = rng.choices(range(args.num_groups), weights=weights, k=args.num_prompts)
    hit_dist = [group_seq.count(g) for g in range(args.num_groups)]
    print(f"[{args.arm} t{args.trial}] empirical group counts: {hit_dist}")

    # Each prompt: system + distinct question for cache-busting
    prompts = []
    for i, g in enumerate(group_seq):
        # Question is unique per seq → forces full continuation each time,
        # but the long system prefix should HIT the cache if group g's
        # snapshot is resident.
        question = f" Question {i} seed={rng.randint(0, 1<<30)}: respond concisely."
        prompts.append(sys_prompts[g] + question)

    print(f"[{args.arm} t{args.trial}] Sending {len(prompts)} requests @ RPS={args.rps}...")
    t_start = time.monotonic()
    records = asyncio.run(run_load(prompts, group_seq, args.port, args.rps, args.max_new_tokens))
    total_wall = time.monotonic() - t_start

    # Per-group stats
    per_group = {g: [] for g in range(args.num_groups)}
    for r in records:
        per_group[r["group"]].append(r)
    total_cached = sum(r["cached"] for r in records)
    total_tokens = sum(args.sys_prompt_tokens for _ in records)
    cache_hit_pct = 100.0 * total_cached / total_tokens
    mean_wall = sum(r["wall"] for r in records) / len(records)
    median_wall = sorted(r["wall"] for r in records)[len(records) // 2]

    print(f"\n=== {args.arm} t{args.trial} results ===")
    print(f"total wall: {total_wall:.1f}s, mean req: {mean_wall*1000:.1f}ms, median: {median_wall*1000:.1f}ms")
    print(f"cache hit %: {cache_hit_pct:.1f}% ({total_cached}/{total_tokens} system-prompt tokens cached)")
    print(f"\nPer-group breakdown:")
    print(f"  {'g':>2} {'count':>5} {'mean_ms':>8} {'cached_pct':>11}")
    for g in range(args.num_groups):
        rs = per_group[g]
        if not rs: continue
        gm = sum(r["wall"] for r in rs) / len(rs) * 1000
        gc = sum(r["cached"] for r in rs)
        gt = args.sys_prompt_tokens * len(rs)
        gpct = 100.0 * gc / gt if gt else 0
        print(f"  {g:>2} {len(rs):>5} {gm:>8.1f} {gpct:>10.1f}%")

    # Save full result
    with open(fname, "w") as f:
        json.dump({
            "arm": args.arm,
            "trial": args.trial,
            "args": vars(args),
            "weights": weights,
            "hit_dist": hit_dist,
            "total_wall_s": total_wall,
            "mean_req_ms": mean_wall * 1000,
            "median_req_ms": median_wall * 1000,
            "cache_hit_pct": cache_hit_pct,
            "total_cached_tokens": total_cached,
            "per_group": {
                str(g): {
                    "n": len(per_group[g]),
                    "mean_ms": (sum(r["wall"] for r in per_group[g]) / len(per_group[g]) * 1000) if per_group[g] else 0,
                    "cached_pct": (100.0 * sum(r["cached"] for r in per_group[g]) /
                                  (args.sys_prompt_tokens * len(per_group[g]))) if per_group[g] else 0,
                } for g in range(args.num_groups)
            },
            "records": records,
        }, f, indent=2)
    print(f"\nSaved to {fname}")


if __name__ == "__main__":
    main()
